#!/bin/bash
rm -rf /tmp/tests/*.e.out
mkdir -p /tmp/tests
t0=$(date +%s)
for t in tests/*.e
do
  echo $t
  ./eniac -g -t 50000 $t > /tmp/$t.out
  cmp /tmp/$t.out $t.out
done
t=$(date +%s)
echo $t $t0 - p | dc